version: '3'

services:
  # Node.js application
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - docker/node-local.env
    volumes:
      - ./:/usr/src/app
  
  # MySQL database
  db:  
    build:
      context: .
      dockerfile: docker/Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psic_sys
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

volumes:
  ignore:      
