version: '3'

services:
  # Node.js application
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    depends_on:
      - db
    ports:
      - "3000:3000"

  # MySQL database
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psic_sys
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"