# Use an official MySQL runtime as a parent image
FROM mysql:8

# Environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=psic_sys
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin

# Copy the database initialization script to the container
COPY docker/init.sql /docker-entrypoint-initdb.d/